### ISSUE TITLE
Doesn't stop ffmpeg.exe at end of stream download

### ISSUE THREAD

**Issue by fzold** [cvzi/mpv-youtube-download#27] opened 2023-07-05 19:46 UTC
I'm working with portable_config,

Download of a stream from m3u8. After stop with 2x CTRL+D the ffmpeg.exe process is not canceled.
The downloaded file has the extension .mp4.part
You cannot rename the file to .mp4 as long as ffmpeg is running.

Canceling a download must end all associated processes.
Please correct.

**Comment by cvzi** [comment] 2023-07-05 20:11
Does the script show the text "Canceling download ..." after you press CTRL+d twice?

**Comment by cvzi** [comment] 2023-07-29 21:20
Closing because can't reproduce

**Closed as not planned by cvzi** 2023-07-29 21:20 UTC
